version: "3.7"
services:

  ros-master:
    hostname: ros_master
    image: ros:noetic-ros-core
    container_name: tortoisebot_ros1_rosmaster
    command: stdbuf -o L roscore
    networks:
      - ros
    environment:
      - ROS_HOSTNAME=ros_master
      - ROS_MASTER_URI=http://ros_master:11311

  tortoisebot_ros1_gazebo:
    image: romu10/romuloperez-cp22:tortoisebot-ros1-gazebo
    container_name: tortoisebot_ros1_gazebo
    restart: "no"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros_master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      - ros
    depends_on:
      - ros-master
    hostname: tortoisebot_ros1_gazebo
    command: bash -c "source devel/setup.bash && roslaunch tortoisebot_gazebo tortoisebot_playground.launch"

  tortoisebot_ros1_slam:
    image: romu10/romuloperez-cp22:tortoisebot-ros1-slam
    container_name: tortoisebot_ros1_slam
    restart: "no"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros_master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      - ros
    depends_on:
      - ros-master
    hostname: tortoisebot_ros1_slam 
    command: bash -c "source devel/setup.bash && roslaunch tortoisebot_slam mapping.launch"

  tortoisebot_ros1_waypoints:
    image: romu10/romuloperez-cp22:tortoisebot-ros1-waypoints
    container_name: tortoisebot_ros1_waypoints
    restart: "no"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros_master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      - ros
    depends_on:
      - ros-master
    hostname: tortoisebot_ros1_waypoints 
    command: bash -c "source devel/setup.bash && rosrun course_web_dev_ros tortoisebot_action_server.py"

  tortoisebot_ros1_webapp:
    image: romu10/romuloperez-cp22:tortoisebot-ros1-webapp
    container_name: tortoisebot_ros1_webapp
    restart: "no"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros_master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      - ros
    depends_on:
      - ros-master
      - tortoisebot_ros1_gazebo
    hostname: tortoisebot_ros1_webapp 
    command: bash -c "cd /simulation_ws && source devel/setup.bash && roslaunch course_web_dev_ros web.launch" 

  tortoisebot_ros1_webapp_server:
    image: romu10/romuloperez-cp22:tortoisebot-ros1-webapp
    container_name: tortoisebot_ros1_webapp_server
    restart: "no"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros_master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    ports:
      - "7000:7000"
    networks:
      - ros
    depends_on:
      - ros-master
      - tortoisebot_ros1_gazebo
    hostname: tortoisebot_ros1_webapp_server 
    command: bash -c "cd /webpage_ws/src/tortoisebot_webapp && python3 -m http.server 7000"
 
networks:
  ros:
    driver: bridge
