version: "3.7"
services:
  tortoisebot_ros1_gazebo:
    image: romu10/romuloperez-cp22:tortoisebot-ros1-gazebo
    container_name: tortoisebot_ros1_gazebo_container
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      - ros_network
    command: bash -c "source devel/setup.bash && roslaunch tortoisebot_gazebo tortoisebot_playground.launch"

networks:
  ros_network:
    driver: bridge
