version: "3.7"
services:

  ros-master:
    hostname: ros_master
    image: ros:noetic-ros-core
    container_name: tortoisebot_ros1_rosmaster
    command: stdbuf -o L roscore
    networks:
      - ros
    environment:
      - ROS_HOSTNAME=ros_master
      - ROS_MASTER_URI=http://ros_master:11311

  tortoisebot_ros1_real:
    image:  romu10/romuloperez-cp22:tortoisebot-ros1-real
    container_name: tortoisebot_ros1_real
    restart: "no"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros_master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      - ros
    depends_on:
      - ros-master
    hostname: tortoisebot_ros1_real
    command: bash -c "source devel/setup.bash && roslaunch tortoisebot_firmware bringup.launch"

  tortoisebot_ros1_slam_real:
    image: romu10/romuloperez-cp22:tortoisebot-ros1-slam-real
    container_name: tortoisebot_ros1_slam_real
    restart: "no"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros_master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    networks:
      - ros
    depends_on:
      - ros-master
    hostname: tortoisebot_ros1_slam_real
    command: bash -c "source devel/setup.bash && roslaunch tortoisebot_slam tortoisebot_slam.launch"

networks:
  ros:
    driver: bridge
