FROM romu10/romuloperez-cp22:tortoisebot_ros1_slam_cartographer_base

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Minimal setup
RUN apt-get update 

# Install gmapping 
RUN apt-get -y install ros-noetic-slam-gmapping

# Install rosbridge_suite
RUN apt-get -y install ros-noetic-rosbridge-suite

# Install web_video_server
RUN apt-get -y install ros-noetic-web-video-server

# Eliminate docker file tortoisebot
RUN cd /simulation_ws/src \
 && rm -rf tortoisebot

# Create dir for course_web_dev_ros
RUN cd /simulation_ws/src \ 
 && mkdir course_web_dev_ros

# git clone tortoisebot_webapp
RUN cd /simulation_ws/src \ 
 && git clone https://github.com/Romu10/tortoisebot_webapp.git \
 && git clone https://github.com/Romu10/WEB-APP-for-Control-the-Tortoisebot.git

# Copy local course_web_dev_ros
COPY course_web_dev_ros /simulation_ws/src/course_web_dev_ros

# Define la variable de entorno SLOT_ROSBRIDGE_PORT
ENV SLOT_ROSBRIDGE_PORT 20001

# Build the Catkin workspace and ensure it's sourced
RUN source /opt/ros/noetic/setup.bash \
 && cd /simulation_ws \
 && catkin_make
RUN echo "source /simulation_ws/devel/setup.bash" >> ~/.bashrc
